#lang racket


#|
(for*/list ([pth (in-list (directory-list
                           "/Users/philip/code/ricoeur/ffi-pkgs/libgit2/include/"))])
  (path->string pth))
|#

'("annotated_commit.rkt"
  "blame.rkt"
  "blob.rkt"
  "branch.rkt"
  "buffer.rkt"
  "checkout.rkt"
  "cherrypick.rkt"
  "clone.rkt"
  "commit.rkt"
  "compiled"
  "config.rkt"
  "cred_helpers.rkt"
  "describe.rkt"
  "diff.rkt"
  "filter.rkt"
  "graph.rkt"
  "ignore.rkt"
  "index.rkt"
  "indexer.rkt"
  "merge.rkt"
  "message.rkt"
  "net.rkt"
  "notes.rkt"
  "object.rkt"
  "odb.rkt"
  "odb_backend.rkt"
  "oid.rkt"
  "oidarray.rkt"
  "pack.rkt"
  "patch.rkt"
  "pathspec.rkt"
  "proxy.rkt"
  "rebase.rkt"
  "refdb.rkt"
  "reflog.rkt"
  "refs.rkt"
  "refspec.rkt"
  "remote.rkt"
  "repository.rkt"
  "reset.rkt"
  "revert.rkt"
  "revparse.rkt"
  "revwalk.rkt"
  "signature.rkt"
  "stash.rkt"
  "status.rkt"
  "strarray.rkt"
  "submodule.rkt"
  "tag.rkt"
  "trace.rkt"
  "transaction.rkt"
  "transport.rkt"
  "tree.rkt"
  "types.rkt")